### ISSUE TITLE
Links broken on "Getting the project" page

### ISSUE THREAD

**Issue by cnovak** [hechoendrupal/drupalconsole.com#81]
The links on https://drupalconsole.com/docs/en/getting/project page lead to a 404.

**Comment by jmolivas** [comment]
Thanks for reporting @cnovak I will take a look and send a fix for this one

**Comment by jmolivas** [comment]
Fixed with PR: https://github.com/hechoendrupal/drupalconsole.com/pull/94

Demo: https://new.drupalconsole.com/docs/en/drupal_console_faq/faq

**Comment by jmolivas** [comment]
I will keep this issue open until we deploy the new site.

**Comment by jmolivas** [comment]
@cnovak  Site was deployed 
https://drupalconsole.com/
https://drupalconsole.com/docs/en/
https://drupalconsole.com/docs/en/getting/project
https://drupalconsole.com/docs/en/drupal_console_faq/faq
